### ISSUE TITLE
License

### ISSUE THREAD

**Issue by bkconrad** [csuttles/oci-vault#2]
Hi there, I was hoping to use this work as a module to deploy Vault on OPC but my organization requires an explicit license declaration. Would you be willing to add one? I would recommend MIT if you don't have a preference.

In any case I appreciate the work you've done here :clap:

**Comment by csuttles** [comment]
I also prefer MIT. Fixed in [https://github.com/csuttles/oci-vault/pull/3 ](https://github.com/csuttles/oci-vault/pull/3)

I hope this works for you, feel free to submit a PRs/bugs as needed.

Thank you! 😄
